{
 "title": "Terraform - NGINX -  LOAD BALANCER",
 "description": "NGINX Plus Prometheus Exporter",
 "tags": [
  "nginx",
  "prometheus",
  "nginx prometheus exporter"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests in last hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginxplus_http_requests_total[1h]))"
    }
   ]
  },
  {
   "title": "Total (2XX from upstream) requests in last hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginxplus_upstream_server_responses{code=\"2xx\"}[1h]))"
    }
   ]
  },
  {
   "title": "Total (4XX from upstream) requests in last hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginxplus_upstream_server_responses{code=\"4xx\"}[1h]))"
    }
   ]
  },
  {
   "title": "Total (5XX from upstream) requests in last hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginxplus_upstream_server_responses{code=\"5xx\"}[1h]))"
    }
   ]
  },
  {
   "title": "Rate of Accepted NGINX Connections",
   "type": "timeseries",
   "description": "Displays the rate of new connections accepted by the NGINX load balancer over time.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(nginxplus_connections_accepted{}[$__rate_interval])",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Upstream Server Response Time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginxplus_upstream_server_response_time{upstream=\"backend\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginxplus_http_requests_total[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "HIT",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(nginxplus_cache_hit_responses{}[$__rate_interval])",
     "legendFormat": "HIT"
    }
   ]
  },
  {
   "title": "MISS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(nginxplus_cache_miss_responses[$__rate_interval])",
     "legendFormat": "MISS"
    }
   ]
  },
  {
   "title": "REVALIDATED",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(nginxplus_cache_revalidated_responses[$__rate_interval])",
     "legendFormat": "REVALIDATED"
    }
   ]
  },
  {
   "title": "EXPIRED",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(nginxplus_cache_expired_responses[$__rate_interval])",
     "legendFormat": "EXPIRED"
    }
   ]
  },
  {
   "title": "Upstream Health Check Server Fails",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(nginxplus_upstream_server_health_checks_fails[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(nginxplus_upstream_server_requests[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Machine Learning", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "NGINX Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    { "expr": "nginx_connections:predicted" },
    { "expr": "nginx_connections:actual" }
   ]
  },
  { "title": "SSL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "SSL Handshakes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rate(nginxplus_ssl_handshakes{}[$__rate_interval])",
     "legendFormat": "SSL Handshakes"
    },
    {
     "expr": "rate(nginxplus_ssl_handshakes_failed[$__rate_interval])",
     "legendFormat": "Handshakes Failed"
    },
    {
     "expr": "rate(nginxplus_ssl_session_reuses[$__rate_interval])",
     "legendFormat": "SSL Reuse"
    }
   ]
  },
  {
   "title": "SSL Session Reuses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "expr": "rate(nginxplus_ssl_session_reuses{}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed SSL Handshakes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "expr": "rate(nginxplus_ssl_handshakes_failed{}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Total requests (rate over 5m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "rate(nginxplus_http_requests_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLOW API (avg > 500ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (upstream) (nginxplus_upstream_server_response_time) < 500",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "upstream_server_response_time (avg)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (upstream) (nginxplus_upstream_server_response_time) <= 500",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "2XX status code (rate over 5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum by (upstream ) (irate(nginxplus_upstream_server_responses{code=\"2xx\"}[5m]))",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "4XX status code (rate over 5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (upstream ) (irate(nginxplus_upstream_server_responses{code=\"4xx\"}[5m]))",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "5XX status code (rate over 5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (upstream ) (irate(nginxplus_upstream_server_responses{code=\"5xx\"}[5m]))",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "NGINX Dashboard Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/nginx/json_access.log\"} |= `` | json"
    }
   ]
  },
  {
   "title": "App Protect Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/app_protect/security.log\"} |= `request_status=\"blocked\"` | logfmt"
    }
   ]
  }
 ]
}